# Matrix Code Lab — Mathematics for Machine Learning
Run each cell and complete the tasks. Try predicting output before executing code.

## 1. Shape of a matrix
**Try first:** predict the shape and total number of elements.

In [2]:
import numpy as np
import pandas as pd

A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print('Shape:', A.shape)
print('Elements:', A.size)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Elements: 6

## 2. Common matrix types
Complete the examples and explain the pattern in each matrix.

In [3]:
row_matrix = np.array([[1, 2, 3]])
column_matrix = np.array([[1], [2], [3]])
zero_matrix = np.zeros((2, 3), dtype=int)
identity_matrix = np.eye(3, dtype=int)
diagonal_matrix = np.diag([2, 5, 8])

print('Row:', row_matrix, row_matrix.shape)
print('Column:\n', column_matrix, column_matrix.shape)
print('Zeros:\n', zero_matrix)
print('Identity:\n', identity_matrix)
print('Diagonal:\n', diagonal_matrix)

Row: [[1 2 3]] (1, 3)
Column:
 [[1]
 [2]
 [3]] (3, 1)
Zeros:
 [[0 0 0]
 [0 0 0]]
Identity:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Diagonal:
 [[2 0 0]
 [0 5 0]
 [0 0 8]]

In [5]:
ones_matrix = np.ones((2,3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]]

## 3. Transpose
Predict how rows and columns change before running the next cell.

In [6]:
print('A shape:', A.shape)
print('A transpose:\n', A.T)
print('A.T shape:', A.T.shape)

A shape: (2, 3)
A transpose:
 [[1 4]
 [2 5]
 [3 6]]
A.T shape: (3, 2)

## 4. ML-style dataset with pandas
Rows are students and columns are features in this example.

In [3]:
df = pd.DataFrame({
    'attendance': [80, 65, 95],
    'study_hours': [6, 3, 8],
    'assignment_score': [90, 70, 96]
}, index=['Student A', 'Student B', 'Student C'])
display(df)
X = df.to_numpy()
print('Shape:', X.shape)
print('Feature means:', X.mean(axis=0))
print('Transpose:\n', X.T)
print('Transpose shape:', X.T.shape)

           attendance  study_hours  assignment_score
Student A          80            6                90
Student B          65            3                70
Student C          95            8                96

Shape: (3, 3)
Feature means: [80.          5.66666667 85.33333333]
Transpose:
 [[80 65 95]
 [ 6  3  8]
 [90 70 96]]
Transpose shape: (3, 3)

## 5. Practice — try without help
1. Create a 3 × 4 matrix and print its shape.
2. Transpose it and print the new shape.
3. Create a 3 × 3 identity matrix.
4. Create a DataFrame with 4 samples and 3 features.
5. Challenge: add a fourth feature and predict the new shape.

In [2]:
# Write your solution below. Avoid copying earlier cells verbatim.


import numpy as np
import pandas as pd
M=np.array([[1, 2, 3, 4], [5, 6,7, 8], [9,10,11,12]])
print("Matrix:",M)
print("Shape:",M.shape)
print("Shape of Transposed M:",M.T.shape)
I=np.eye(3,dtype=int)
print("Identity Matrix:",I)
D=pd.DataFrame({
    'attendance':[80,65,95,90],
    'study_hours':[6,3,8,7],
    'assignment_score':[90,70,96,85]
},index=['Student A','Student B','Student C','Student D'])
display(D)
D["Sleep_hours"]=[7,5,6,8]
print("Shape of D:",D.shape)

Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Shape of Transposed M: (4, 3)
Identity Matrix: [[1 0 0]
 [0 1 0]
 [0 0 1]]

           attendance  study_hours  assignment_score
Student A          80            6                90
Student B          65            3                70
Student C          95            8                96
Student D          90            7                85

Shape of D: (4, 4)